### DISCUSSION TITLE
Styles: docs and CSS variables

### DISCUSSION THREAD

**Discussion by andrecasal** [epicweb-dev/epic-stack#139] [Ideas]
I've recently migrated my platform to the Epic Stack's latest version.

Styles keep being a bit of a pain because there are custom styles configured in `tailwind.config.ts` and they are spread throughout the code base.
<details>
  <summary>Screenshot of a search for the "-night-" class</summary>
  
![Screenshot 2023-06-05 at 19 05 25](https://github.com/epicweb-dev/epic-stack/assets/22457463/e2751764-29c8-43d9-9741-75dfd63d3187)
</details>

It's a bit painful to delete all those 👆 classes.

I'd like to propose two things:
- Add documentation around styling
- Implement the theme switch by changing CSS Variable's values

### Implement the theme switch by changing CSS Variable's values

Change the CSS Variable's **values** according to the theme:
`tailwind.css`:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

:root {
	--color-background: white;
	--color-foreground: black;
	--color-primary: green;
	--color-accent: orange;
	--color-success: black;
	--color-info: black;
	--color-warning: black;
	--color-danger: black;
}

:root.dark {
	--color-background: black;
	--color-foreground: white;
}
```

Use those CSS variables in your **semantic** styles:
`tailwind.config.ts`:
```ts
export default {
	content: ['./app/**/*.{ts,tsx,jsx,js}'],
	darkMode: 'class',
	theme: {
		extend: {
			colors: {
				background: 'var(--color-background)', // used in <body className="bg-background text-foreground">
				foreground: 'var(--color-foreground)', // used in <body className="bg-background text-foreground">
				primary: 'var(--color-primary)',
				accent: 'var(--color-accent)',
				success: 'var(--color-success)',
				info: 'var(--color-info)',
				warning: 'var(--color-warning)',
				danger: 'var(--color-danger)',
			},
		}
	}
}
```

This way you can build your entire app with your semantic styles, while still having a single source of truth in your `tailwind.css` file.

The only down-side to this is that we lose the ability to see the colors in VS Code and we see the CSS variable instead:
![Screenshot 2023-06-05 at 19 37 18](https://github.com/epicweb-dev/epic-stack/assets/22457463/c78cf526-aeda-4b84-af22-ff47a58d6515)
