### DISCUSSION TITLE
Minimum target size

### DISCUSSION THREAD

**Discussion by andrecasal** [epicweb-dev/epic-stack#162] [Ideas]
On my apps I use custom `min-w-tap` and `min-h-tap` Tailwind classes that adapt to the user's pointer ([24px for cursors](https://w3c.github.io/wcag/understanding/target-size-minimum.html) and [44px for fingers](https://www.w3.org/WAI/WCAG21/Understanding/target-size.html)).

`tailwind.css`:
```css
/* Tap targets */
:root {
	--min-tap-target: 24px;
}

@media (pointer: coarse) {
	:root {
		--min-tap-target: 44px;
	}
}
```

`tailwind.config.ts`:
```ts
export default {
	...
	theme: {
		extend: {
			minWidth: {
				tap: 'var(--min-tap-target)',
			},
			minHeight: {
				tap: 'var(--min-tap-target)',
			},
		},
	},
	...
} satisfies Config
```

If you find this useful, I'd be happy to add this to [this PR](https://github.com/epicweb-dev/epic-stack/pull/146).
