### DISCUSSION TITLE
🚁 Preview Apps (or review apps)

### DISCUSSION THREAD

**Discussion by bryantbrock** [epicweb-dev/epic-stack#716] [Show and tell]
I wanted to have preview apps for my epic-stack (started) remix application. I found this article on fly.io that outlines getting started, but a few modifications were needed so I'd thought I'd share my final GH Action for anyone interested. Would be cool to see this up on the epic-stack starter.

```yml
name: 🚁 Preview

on:
  pull_request:
    types: [opened, reopened, synchronize, closed]

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
  FLY_REGION: your-fav-region
  FLY_ORG: your-org-slug

jobs:
  deploy:
    name: 🚀 Deploy
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.deploy.outputs.url }}
    concurrency:
      group: pr-${{ github.event.number }}

    environment:
      name: review
      url: ${{ steps.deploy.outputs.url }}

    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v4

      - name: 🚚 Move Dockerfile
        run: |
          mv ./other/Dockerfile ./Dockerfile
          mv ./other/.dockerignore ./.dockerignore

      - name: 🚀 Deploy Preview
        id: deploy
        uses: superfly/fly-pr-review-apps@1.2.0
        with:
          name: your-app-name-${{ github.event.number }}
          config: fly.preview.toml

      - name: 🎈 Setup Fly
        uses: superfly/flyctl-actions/setup-flyctl@v1.4

      - name: ✨ Finalize
        run: |
          flyctl secrets set ALLOW_INDEXING=false SESSION_SECRET=$(openssl rand -hex 32) INTERNAL_COMMAND_TOKEN=$(openssl rand -hex 32) HONEYPOT_SECRET=$(openssl rand -hex 32) --app ${{ steps.deploy.outputs.name }}
          flyctl consul attach --app ${{ steps.deploy.outputs.name }}

```
