### DISCUSSION TITLE
LiteFS + Caching

### DISCUSSION THREAD

**Discussion by heauton** [epicweb-dev/epic-stack#859] [Q&A] [answered]
I was inspecting `litefs.yml` and it seemed to me that LiteFS can only proxy a single SQLite file:

```yml
proxy:
  ...
  db: '${DATABASE_FILENAME}'
```

Here are some relevant links I found:
https://community.fly.io/t/litefs-multiple-databases/15595
https://community.fly.io/t/litefs-how-to-work-with-multiple-databases/15472

I am guessing `updatePrimaryCacheValue` is what acts as a proxy for `cache.db` (please correct me if I am wrong!)

If for some reason I don't use LiteFS as my main database (use something else e.g., other hosted SQLite, Postgres, etc.), but still use LiteFS only for caching purposes, do I still need to keep this `proxy` config in `litefs.yml`? If so, should I update it to look something like this?

```yml
proxy:
  ...
  db: '${CACHE_DATABASE_FILENAME}'
```

Or is it safe to delete this `proxy` config? I am not sure how this would affect Epic Stack setup, so any help is appreciated. Thanks!
